index:
    path: /
    controller: App\Controller\PostController::indexAction

addPost:
    path: /add
    controller: App\Controller\PostController::addAction


showPost:
    path: /show/{id}
    controller: App\Controller\PostController::showAction

editPost:
    path: /edit/{id}
    controller: App\Controller\PostController::editAction

deletePost:
    path: /delete/{id}
    controller: App\Controller\PostController::deleteAction